# Backend TH-GUARD — acesso total
user thguard-backend
topic readwrite thguard/#

# Node-RED — acesso total
user nodered
topic readwrite #

# Sensores — acesso aos topicos thguard
user thguard
topic readwrite thguard/#
